#!/bin/bash -f

git fetch origin --prune
git remote update --prune
git branch -r | awk '{print $1}' | egrep -v -f /dev/fd/0 <(git branch -vv | grep origin) | awk '{print $1}' | xargs -r git branch -D
git gc --prune=now

